[package]
name = "rayon_logs"
version = "0.1.1"
authors = ["frederic wagner <frederic.wagner@imag.fr>", "Quentin Guilloteau <quentin.guilloteau@grenoble-inp.org>"]
description = "Traces for the rayon work-stealing library"
license = "Apache-2.0/MIT"
repository = "https://github.com/wagnerf42/rayon-logs"
readme = "README.md"
keywords = ["parallel", "thread", "concurrency", "join", "performance"]
categories = ["concurrency"]
exclude = [
    "TODO"
]

[profile.release]
debug = true

[dependencies]
rayon="*" #{path="../clone_rayon"}
time="^0"
serde="^1"
serde_json="^1"
serde_derive="^1"
itertools="^0"
rand="^0"
hwloc="*"
libc="*"

[dev-dependencies]
criterion="*"

[[bench]]
name = "storage"
harness = false
