[package]
name = "rayon_logs"
version = "0.1.0"
authors = ["frederic wagner <frederic.wagner@imag.fr>", "Quentin Guilloteau <quentin.guilloteau@grenoble-inp.org>"]
description = "Traces for the rayon work-stealing library"
license = "Apache-2.0/MIT"
repository = "https://github.com/wagnerf42/rayon-logs"
readme = "README.md"
keywords = ["parallel", "thread", "concurrency", "join", "performance"]
categories = ["concurrency"]
exclude = [
    "TODO"
]

[dependencies]
rayon="1.*.*"
time="0.1.*"
serde="1.*.*"
serde_json="*"
serde_derive="*"
itertools="0.*.*"
rand="0.4.*"
