[package]
name = "rayon_logs"
version = "0.1.0"
authors = ["frederic wagner <frederic.wagner@imag.fr>"]

[dependencies]
rayon="*"
time="*"
serde="*"
serde_json="*"
serde_derive="*"
itertools="*"
lazy_static="*"
rand="*"
